---

- hosts: all
  become: true
  tasks:

  - name: Update dnf repository cache
    dnf:
      update_cache: yes

  - name: Install Tree package
    dnf:
      name: tree
      state: latest 

  - name: Install or Update httpd
    dnf:
      name : httpd
      state: latest

  - name: Start httpd service
    service:
      name: httpd
      state: started 
