---

- hosts: all
  become: true
  tasks:

  - name: Install or Update httpd and tree on Fedora 39
    ansible.builtin.dnf:
      name:
        - httpd
        - tree
      state: latest
      update_cache: yes
    when: ansible_distribution == "Fedora" and ansible_distribution_version == "39"

  - name: Start httpd service
    ansible.builtin.service:
      name: httpd
      state: started

  - name: Install nano and tree on Fedora 38
    ansible.builtin.dnf:
      name:
        - nano
        - tree
      state: latest
    when: ansible_distribution == "Fedora" and ansible_distribution_version == "38"
