---

- hosts: all
  become: true
  tasks:

  - name: Update DNF cache (Fedora)
    tags: always
    ansible.builtin.dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "Fedora"

- hosts: all
  become: true
  tasks:

  - name: Add user Donna to all machines
    tags: always
    ansible.builtin.user:
      name: donna
      groups: webgrp

- hosts: web_server
  become: true
  tasks:

  - name: Install httpd and Tree for Web server Fedora 39.
    tags: webserver,tree,fedora39
    ansible.builtin.dnf:
      name:
        - httpd
        - tree
      state: latest
    when: ansible_distribution == "Fedora" and ansible_distribution_version == "39"

  - name: Copy default html file for site.
    tags: webserver,tree,fedora39
    ansible.builtin.copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

  - name: Start httpd service
    tags: webserver,tree,fedora39
    ansible.builtin.service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "Fedora" and ansible_distribution_version == "39"

  - name: Change ServerAdmin email address in httpd file."
    tags: webserver,tree,fedora39
    ansible.builtin.lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin someone@somewhere.com
    when: ansible_distribution == "Fedora" and ansible_distribution_version == "39"
    register: linehttpd

  - name: Restart httpd services if changes to httpd file
    tags: webserver,tree,httpd
    ansible.builtin.service:
      name: httpd
      state: restarted
    when: linehttpd.changed

- hosts: file_server
  become: true
  tasks:

  - name: Install unzip package for File Server Fedora 39.
    tags: fileserver,unzip
    ansible.builtin.dnf:
      name:
        - upzip
      state: present

- hosts: app_server
  become: true
  tasks:

  - name: Install nano and tree on Application server Fedora 38.
    tags: appserver,nano,tree
    ansible.builtin.dnf:
      name:
        - nano
        - tree
      state: latest
    when: ansible_distribution == "Fedora" and ansible_distribution_version == "38"
