---

- hosts: all
  become: true
  tasks:

  - name: Update dnf repository cache
    ansible.builtin.dnf:
      update_cache: yes

  - name: Install Tree package
    ansible.builtin.dnf:
      name: tree
      state: latest 
    when: ansible_distribution == "Fedora" 

  - name: Install or Update httpd
    ansible.builtin.dnf:
      name : httpd
      state: latest
    when: ansible_distribution == "Ubuntu" 

  - name: Start httpd service
    ansible.builtin.service:
      name: httpd
      state: started 
