---

- hosts: all
  become: true
  tasks:

  - name: Update DNF cache (Fedora)
    tags: always
    ansible.builtin.dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "Fedora"

- hosts: web_server
  become: true
  tasks:

  - name: Install httpd and Tree for Web server Fedora 39.
    tags: webserver,tree,fedora39
    ansible.builtin.dnf:
      name:
        - httpd
        - tree
      state: latest
    when: ansible_distribution == "Fedora" and ansible_distribution_version == "39"

  - name: Start httpd service
    tags: webserver,tree,fedora39
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "Fedora" and ansible_distribution_version == "39"

- hosts: file_server
  become: true
  tasks:

  - name: Install unzip package for File Server Fedora 39.
    tags: fileserver,unzip
    ansible.builtin.dnf:
      name:
        - upzip
      state: present

- hosts: app_server
  become: true
  tasks:

  - name: Install nano and tree on Application server Fedora 38.
    tags: appserver,nano,tree
    ansible.builtin.dnf:
      name:
        - nano
        - tree
      state: latest
    when: ansible_distribution == "Fedora" and ansible_distribution_version == "38"
