---

- hosts: all
  become: true
  tasks:

  - name: Update DNF Cache
    ansible.builtin.dnf:
      update_cache: yes
    when: ansible_distribution == "Fedora"

- hosts: web_server
  become: true
  tasks:

  - name: Stop httpd services for Web server.
    ansible.builtin.service:
      name: httpd
      state: stopped
    when: ansible_distribution == "Fedora" and ansible_distribution_version == "39"

  - name: Uninstall httpd ands tree packages.
    ansible.builtin.dnf:
      name:
        - httpd
        - tree
      state: absent
    when: ansible_distribution == "Fedora" and ansible_distribution_version == "39"

- hosts: file_server
  become: true
  tasks:

  - name:
    ansible.builtin.dnf:
      name:
        - unzip
      state: absent
    when: ansible_distribution == "Fedora" and ansible_distribution_version == "39"

- hosts: app_server
  become: true
  tasks:

  - name: Uninstall nano editor and tree packages.
    ansible.builtin.dnf:
      name:
        - nano
        - tree
      state: absent
    when: ansible_distribution == "Fedora" and ansible_distribution_version == "38"

