---

- hosts: all
  become: true
  tasks:

  - name: Stop httpd services.
    ansible.builtin.service:
      name: httpd
      state: stopped
    when: ansible_distribution == "Fedora" and ansible_distribution_version == "39"

  - name: Uninstall httpd ands tree packages.
    ansible.builtin.dnf:
      name:
        - httpd
        - tree
      state: absent
    when: ansible_distribution == "Fedora" and ansible_distribution_version == "39"

  - name: Uninstall nano editor and tree packages.
    ansible.builtin.dnf:
      name:
        - nano
        - tree
      state: absent
    when: ansible_distribution == "Fedora" and ansible_distribution_version == "38"

